export enum AWSErrorStatus {
  UN_KNOWN_ENDPOINT = "UnknownEndpoint",
}

export enum ErrorStatus {
  STOP_INTERVAL_PULLING_MESSAGE = "STOP_INTERVAL_PULLING_MESSAGE",
  IS_NOT_VALID_REQUIRE_MESSAGE_PARAMS = "IS_NOT_VALID_REQUIRE_MESSAGE_PARAMS",
  IS_NOT_VALID_REQUIRE_AWS_KEY = "IS_NOT_VALID_REQUIRE_AWS_KEY",
  IS_NOT_VALID_REQUIRE_AWS_ENDPOINT_INFO = "IS_NOT_VALID_REQUIRE_AWS_ENDPOINT_INFO",
  MESSAGE_DELETE_FAILED = "MESSAGE_DELETE_FAILED",
}