export enum CacheKeyStatus {
  INTERVAL_PULLING_MESSAGE_ID = "intervalPullingMessageId",
}

export enum ErrorStatus {
  STOP_INTERVAL_PULLING_MESSAGE = "STOP_INTERVAL_PULLING_MESSAGE",
  IS_NOT_VALID_REQUIRE_MESSAGE_PARAMS = "IS_NOT_VALID_REQUIRE_MESSAGE_PARAMS",
  MESSAGE_DELETE_FAILED = "MESSAGE_DELETE_FAILED",
}
